opto.trace.errors.ExecutionError
================================

.. currentmodule:: opto.trace.errors

.. autoexception:: ExecutionError